[translation_by]
author = "Theysa"

[HelpMenu.main]
config   = "Manage config options for Lithic."
delete   = "Remove mods and backups."
download = "Download a Vintage Story executable."
help     = "Print this message or the help of the given subcommand(s)"
info     = "Get more information about the mod specified."
install  = "Install a specific mod. Must use the mod_id, Example: ./Lithic install alchemy"
list     = "List installed mods and their versions and any missing dependencies. Running sync first will show any available updates to your mods."
misc     = "Miscellaneous items for Lithic, like shell auto-completion and 1-click mod installation."
modpack  = "Create, download, update modpacks for VintageStory."
search   = "Search the mod website for new mods, Example: ./Lithic search -q magic"
self     = "Manage the Lithic binary; Check for updates, perform updates."
sync     = "Checks with the VintageStory mods website for any updates to mods you have installed. Run update after this command to update your mods."
update   = "Updates a specific mod OR all mods installed. Runs sync after completion."

[HelpMenu.sync]
sync_game_versions = "Sync a local list of all game versions from the api. This is used with version pinning to ensure we have accurate version numbers."
sync_game_versions.long = [
  "Sync a local list of all game versions from the api. This is used with version pinning to ensure we have accurate version numbers.",
  "linux/mac: [~/.config/lithic/game-versions.json]",
  "windows: [%appdata%/lithic/game-versions.json]",
]
sync_search_db = "Sync the mod info from the api endpoint /api/mods and save it locally."
sync_search_db.long = '''
Sync the mod info from the api endpoint /api/mods and save it locally.
This file is used for the search command so we are not making a ton of unneeded api calls and to obtain the mod-id for mods that don't provide one in their modinfo.json
linux/mac: [~/.config/lithic/mod-id-sync.json.]
windows: [%appdata%/lithic/mod-id-sync.json]
'''

[HelpMenu.list]

[HelpMenu.update]

[HelpMenu.search]

[HelpMenu.config]

[HelpMenu.misc]

[HelpMenu.download]

[HelpMenu.info]

[HelpMenu.modpack]

[HelpMenu.self]

[HelpMenu.delete]
